# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d965c55f88efbfb46dc44100daefe53f9e5c90050a3f89af04193c8779aa32d1f00eff8b8593cfa54280ba1c729f629eb7a7da7933198c285d9fe23b2d80ac7

test:
  secret_key_base: 6b02ed45c88d82683fe791dd258494ac081df7f438355cdf7293d2c1b9b89ce753a77e05963aff9dfb3097449a18912bd51b3d1bb3f3df4effceb0fbd1138db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
